import { Employee } from "@/interfaces/employee";
import { SelectOption } from "@/interfaces/common";

export const ROLE_OPTIONS: SelectOption[] = [
  { label: "Quản lý", value: "manager" },
  { label: "Nhân viên", value: "employee" },
];

export const DEPARTMENT_OPTIONS: SelectOption[] = [
  { label: "Kỹ thuật", value: "Kỹ thuật" },
  { label: "Kinh doanh", value: "Kinh doanh" },
  { label: "Nhân sự", value: "Nhân sự" },
  { label: "Kế toán", value: "Kế toán" },
  { label: "Marketing", value: "Marketing" },
];
export const MOCK_EMPLOYEES: Employee[] = [
  {
    id: 1,
    username: "appuser01",
    fullName: "Nguyễn Văn An",
    email: "an.nguyen@company.vn",
    phone: 912345678,
    position: "Trưởng phòng",
    department: "Kỹ thuật",
    role: "manager",
    joinDate: "2021-03-15",
    baseSalary: 35000000,
  },
  {
    id: 2,
    username: "tran.binh",
    fullName: "Trần Thị Bình",
    email: "binh.tran@company.vn",
    phone: 987654321,
    position: "Lập trình viên",
    department: "Kỹ thuật",
    role: "employee",
    joinDate: "2022-07-01",
    baseSalary: 18000000,
  },
  {
    id: 3,
    username: "le.cuong",
    fullName: "Lê Mạnh Cường",
    email: "cuong.le@company.vn",
    phone: 903112233,
    position: "Nhân viên kinh doanh",
    department: "Kinh doanh",
    role: "employee",
    joinDate: "2023-01-10",
    baseSalary: 12000000,
  },
  {
    id: 4,
    username: "pham.dung",
    fullName: "Phạm Thùy Dung",
    email: "dung.pham@company.vn",
    phone: 938556677,
    position: "Chuyên viên nhân sự",
    department: "Nhân sự",
    role: "employee",
    joinDate: "2020-11-20",
    baseSalary: 14000000,
  },
  {
    id: 5,
    username: "hoang.em",
    fullName: "Hoàng Văn Em",
    email: "em.hoang@company.vn",
    phone: 977889900,
    position: "Kế toán trưởng",
    department: "Kế toán",
    role: "manager",
    joinDate: "2019-05-02",
    baseSalary: 28000000,
  },
  {
    id: 6,
    username: "vu.giang",
    fullName: "Vũ Hương Giang",
    email: "giang.vu@company.vn",
    phone: 966123456,
    position: "Content Marketing",
    department: "Marketing",
    role: "employee",
    joinDate: "2024-02-19",
    baseSalary: 11000000,
  },
];
